### ISSUE TITLE
The repo's link points to an outdated doc version

### ISSUE THREAD

**Issue by j-maas** [Chadtech/elm-relational-database#4]
The link at the top of the repo, next to the description, points to an outdated version of the documentation (https://package.elm-lang.org/packages/Chadtech/elm-relational-database/1.2.1/).

It should maybe point to https://package.elm-lang.org/packages/Chadtech/elm-relational-database/latest/.

**Comment by Chadtech** [comment]
Thank you. (Not sure why I just did 👍  at the time instead of actually changing the link 😄 )
